---
- hosts: FW
  connection: local
  gather_facts: false
  become: false
  collections:
    - paloaltonetworks.panos
    - ansible.utils
  tasks:
    - name: Run commmand 'show interfaces' on firewalls running PAN-OS.
      paloaltonetworks.panos.panos_op:
        cmd: show interface all
      register: result
    - name: Convert to Python dictionary with xmltodict
      set_fact:
        interfaces: "{{ result['stdout_xml'] | ansible.utils.from_xml('xmltodict') }}"
    - name: Print interface output to the console
      debug:
        msg: "{{ interfaces['response']['result']['hw']['entry'] }}"
