---
- name: Change Palo Alto firewall hostname
  hosts: paloalto
  connection: local
  gather_facts: no

  tasks:
    - name: Set new hostname
      panos_device:
        ip_address: "{{ ansible_host }}"
        username: "{{ username }}"
        password: "{{ password }}"
        operation: set
        xpath: /config/devices/entry[@name='localhost.localdomain']/deviceconfig/system/hostname
        element: "{{ new_hostname }}"

    - name: Commit changes
      panos_commit:
        ip_address: "{{ 10.10.10.233 }}"
        username: "{{ admin }}"
        password: "{{ Daud@123 }}"
