---
#------------------------------------------------------------------------
# HELLO WORLD
#------------------------------------------------------------------------
- hosts: FW
  connection: local
  gather_facts: False
  become: False
  collections:
    - paloaltonetworks.panos
    - ansible.utils

  tasks:
  - name: "Run command 'show interfaces' on firewalls running PAN-OS."
    shell: "your_command_here"
    args:
      executable: /bin/bash
    register: show_interfaces_output

  - debug:
      var: show_interfaces_output.stdout_lines

    - name: "Convert to Python dictionary with xmltodict"
      set_fact:
        interfaces: "{{ result['stdout_xml'] | ansible.utils.from_xml('xmltodict') }}"

    - name: "Print interface output to the console"
      debug:
        msg: "{{ interfaces['response']['result']['hw']['entry'] }}"
