---
- name: Configure PAN-OS
  hosts: palo_alto_devices
  gather_facts: no  # Assuming you don't need facts gathering

  tasks:
    - name: Configure Security Rule
      paloaltonetworks.panos.panos_security_rule:
        ip_address: "{{ provider.ip_address }}"
        username: "{{ provider.username }}"
        password: "{{ provider.password }}"
        rule_name: "Allow SSH"
        source_zones: ["trust"]
        destination_zones: ["untrust"]
        source_addresses: ["any"]
        destination_addresses: ["any"]
        applications: ["ssh"]
        action: "allow"
        description: "Allow SSH traffic"
      delegate_to: localhost

    # Add more tasks as needed for your PAN-OS configuration
