# playbook.yml
---
- name: Configure Firewall
  hosts: PA-Firewall
  gather_facts: no

  tasks:
    - name: Display Firewall Configuration
      debug:
        msg: |
          Hostname: {{ firewall.hostname }}
          Admin User: {{ firewall.admin_user }}
          Admin Password: {{ firewall.admin_password }}
          Management IP: {{ firewall.management_ip }}

