# playbook.yml
---
- name: Configure Firewall
  hosts: firewall_device
  gather_facts: no

  vars_files:
    - vars.yml

  tasks:
    - name: Display Firewall Configuration
      debug:
        msg: |
          Hostname: {{ firewall.hostname }}
          Admin User: {{ firewall.admin_user }}
          Admin Password: {{ firewall.admin_password }}
          Management IP: {{ firewall.management_ip }}
