- name: Configure Palo Alto Networks Interfaces
  hosts: palo_alto_devices
  gather_facts: yes
  #connection: local

  tasks:
    - name: Configure Ethernet1/1 interface
      panos_interface:
        provider: "{{ provider }}"
        name: "ethernet1/1"
        mode: "layer3"
        comment: "Configured by Ansible"
        state: "present"
        mtu: 1500
        enable: yes
        ip_address: "192.168.1.1/24"
