---
- name: Configure Palo Alto Networks Interface
  hosts: palo_alto_devices
  gather_facts: no
  collections:
    - paloaltonetworks.panos

  vars:
    provider:
      username: admin
      password: Daud@123
      ip_address: 10.10.10.233
      port: 443
      validate_certs: no
      
  tasks:
    - name: Configure Ethernet1/1 interface
      panos_network_interface:
        provider: "{{ provider }}"
        name: "ethernet1/1"
        zone: "untrust"
        mode: "layer3"
        comment: "Configured by Ansible"
        enable: yes
        ipv4:
          address: "192.168.1.1/24"
        commit: yes
