---
- name: Get Firewall Name
  hosts: paloalto
  gather_facts: no
  tasks:
    - name: Gather system information
      panos_op:
        provider:
          hostname: "{{ paloalto_host }}"
          username: "{{ paloalto_user }}"
          password: "{{ paloalto_password }}"
        cmd: "<show><system><info></info></system></show>"
      register: system_info

    - name: Display Firewall Name
      debug:
        var: system_info['stdout']['result']['system']['hostname']
