---
- name: Configure Palo Alto Networks Interface
  hosts: Switch1
  gather_facts: no
  collections:
    - paloaltonetworks.panos

  - name: ethernet1/2 as static in zone dmz
  panos_interface:
    provider: '{{ provider }}'
    if_name: "ethernet1/2"
    mode: "layer3"
    ip: ["10.1.1.1/24"]
    enable_dhcp: false
    zone_name: "dmz"
    # Add more tasks for other interfaces as needed
