---
- name: Configure Palo Alto Networks Interface
  hosts: Switch1
  gather_facts: no
  collections:
    - paloaltonetworks.panos

  tasks:
    - name: Configure Ethernet1/1 interface
      panos_interface:
        provider: "{{ provider }}"
        name: "ethernet1/1"
        mode: "layer3"
        comment: "Configured by Ansible"
        state: "present"
        mtu: 1500
        enable: yes
        ip_address: "192.168.1.1/24"

  tasks:
  - name: Commit changes
    panos_commit:
      provider: "{{ provider }}"
    delegate_to: localhost   

    # Add more tasks for other interfaces as needed
