---
- name: Assign IP Address to Ethernet 1/1
  hosts: palo_alto_devices
  gather_facts: no

  tasks:
    - name: Configure Interface Ethernet 1/1
      paloaltonetworks.panos.panos_network_interface:
        ip_address: "{{ provider.ip_address }}"
        username: "{{ provider.username }}"
        password: "{{ provider.password }}"
        interface: "ethernet1/1"
        ipv4:
          address: "192.168.1.1/24"  # Replace with your desired IP address and subnet mask
        commit: true
      delegate_to: localhost
