---
- name: Configure Palo Alto Networks Interface
  hosts: Switch1
  gather_facts: no
  collections:
    - paloaltonetworks.panos

  tasks:
    - name: Configure Ethernet1/1 interface
      panos_network_interface:
        provider: "{{ provider }}"
        name: "ethernet1/1"
        zone: "untrust"
        mode: "layer3"
        comment: "Configured by Ansible"
        enable: yes
        ipv4:
          address: "192.168.1.1/24"
        commit: yes
    # Add more tasks for other interfaces as needed
